### ISSUE TITLE
Unable to run composerProvision

### ISSUE THREAD

**Issue by cwcrawley** [buzzingpixel/executive-ee#6]
when I run `php ee executive composerProvision` I get an error that the folder public/themes/user/ doesn't exist, which is technically true because it should be public_html/themes/user.

How/Where do I set the override? I can't seem to find anything in the docs for this..

**Comment by tjdraper** [comment]
Hi Carl,

You can set the public directory override as an option in the "extra" key object of composer.json: https://github.com/buzzingpixel/executive-ee/blob/master/docs/composer-provisioning.md#publicdir

**Comment by cwcrawley** [comment]
Perfect. Thanks.
